# Generated by Django 6.0 on 2025-12-27 19:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_departement", models.CharField(max_length=100)),
                ("nom_region", models.CharField(max_length=100)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secteur",
                    models.CharField(
                        choices=[
                            ("AGRICULTURE", "Agriculture"),
                            ("ELEVAGE", "Elevage"),
                            ("PECHE", "Pêche"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filiere", models.CharField(max_length=100)),
                ("volume_tonnes", models.FloatField()),
                ("annee", models.IntegerField(default=2025)),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productions",
                        to="core.departement",
                    ),
                ),
            ],
        ),
    ]
